package bagian_operator;
import bagian_operator.input_data_mhs;
import java.awt.Panel;

public class dashboard_opt extends javax.swing.JFrame {
    input_data_mhs anu_input;
    buat_kelas anu_kelas;
    input_asdos anu_asdos;
    Panel panel;
    login_operator login;
    
    public dashboard_opt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_alas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_input_mhs = new javax.swing.JPanel();
        lbl_input_mhs = new javax.swing.JLabel();
        pnl_buat_kelas = new javax.swing.JPanel();
        lbl_buat_kelas = new javax.swing.JLabel();
        pnl_logout = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnl_input_asisten = new javax.swing.JPanel();
        lbl_input_asisten = new javax.swing.JLabel();
        pnl_atas = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        panel_alas1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        panel_alas.setBackground(new java.awt.Color(245, 245, 245));
        panel_alas.setLayout(new java.awt.CardLayout());
        panel_alas.add(jLabel2, "card2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 727));
        setSize(new java.awt.Dimension(1365, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 225, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bagian_operator/icon/UIN dash.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 74, -1, -1));

        pnl_input_mhs.setBackground(new java.awt.Color(255, 255, 255));
        pnl_input_mhs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_input_mhs.setPreferredSize(new java.awt.Dimension(280, 40));

        lbl_input_mhs.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_input_mhs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_input_mhs.setText("Input Mahasiswa");
        lbl_input_mhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_input_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_input_mhsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_input_mhsLayout = new javax.swing.GroupLayout(pnl_input_mhs);
        pnl_input_mhs.setLayout(pnl_input_mhsLayout);
        pnl_input_mhsLayout.setHorizontalGroup(
            pnl_input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        pnl_input_mhsLayout.setVerticalGroup(
            pnl_input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_input_mhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, -1));

        pnl_buat_kelas.setBackground(new java.awt.Color(255, 255, 255));
        pnl_buat_kelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_buat_kelas.setPreferredSize(new java.awt.Dimension(280, 40));

        lbl_buat_kelas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_buat_kelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buat_kelas.setText("Buat Kelas Praktikum");
        lbl_buat_kelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_buat_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_buat_kelasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_buat_kelasLayout = new javax.swing.GroupLayout(pnl_buat_kelas);
        pnl_buat_kelas.setLayout(pnl_buat_kelasLayout);
        pnl_buat_kelasLayout.setHorizontalGroup(
            pnl_buat_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_buat_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        pnl_buat_kelasLayout.setVerticalGroup(
            pnl_buat_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_buat_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_buat_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        pnl_logout.setBackground(new java.awt.Color(255, 255, 255));
        pnl_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_logout.setPreferredSize(new java.awt.Dimension(280, 40));

        lbl_logout.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logout.setText("Logout");
        lbl_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_logoutLayout = new javax.swing.GroupLayout(pnl_logout);
        pnl_logout.setLayout(pnl_logoutLayout);
        pnl_logoutLayout.setHorizontalGroup(
            pnl_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        pnl_logoutLayout.setVerticalGroup(
            pnl_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_logout, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Operator");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 27, -1, -1));

        pnl_input_asisten.setBackground(new java.awt.Color(255, 255, 255));
        pnl_input_asisten.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_input_asisten.setPreferredSize(new java.awt.Dimension(280, 40));

        lbl_input_asisten.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_input_asisten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_input_asisten.setText("Input Asisten Dosen");
        lbl_input_asisten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_input_asisten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_input_asistenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_input_asistenLayout = new javax.swing.GroupLayout(pnl_input_asisten);
        pnl_input_asisten.setLayout(pnl_input_asistenLayout);
        pnl_input_asistenLayout.setHorizontalGroup(
            pnl_input_asistenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(pnl_input_asistenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_input_asisten, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
        );
        pnl_input_asistenLayout.setVerticalGroup(
            pnl_input_asistenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(pnl_input_asistenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_input_asisten, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_input_asisten, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 720));

        pnl_atas.setBackground(new java.awt.Color(61, 60, 60));
        pnl_atas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_atas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_title.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("Welcome");
        pnl_atas.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 20, 310, -1));

        getContentPane().add(pnl_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1130, 70));

        panel_alas1.setBackground(new java.awt.Color(245, 245, 245));
        panel_alas1.setLayout(new java.awt.CardLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bagian_operator/icon/wall3.jpg"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panel_alas1.add(jLabel3, "card2");

        getContentPane().add(panel_alas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 1130, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_input_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_input_mhsMouseClicked
        // TODO add your handling code here:
        pnl_buat_kelas.setBackground(java.awt.Color.decode("#ffffff"));
        pnl_input_asisten.setBackground(java.awt.Color.decode("#ffffff"));
        lbl_buat_kelas.setForeground(java.awt.Color.decode("#000000"));
        lbl_input_asisten.setForeground(java.awt.Color.decode("#000000"));
        pnl_input_mhs.setBackground(java.awt.Color.decode("#30AD5B"));
        lbl_input_mhs.setForeground(java.awt.Color.decode("#ffffff"));
        lbl_title.setText("Input Data Mahasiswa");
        muncul_input_mhs();
    }//GEN-LAST:event_lbl_input_mhsMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // TODO add your handling code here:
        pnl_logout.setBackground(java.awt.Color.decode("#E22121"));
        lbl_logout.setForeground(java.awt.Color.decode("#ffffff"));
        logout();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_input_asistenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_input_asistenMouseClicked
        // TODO add your handling code here:
        pnl_input_mhs.setBackground(java.awt.Color.decode("#ffffff"));
        pnl_buat_kelas.setBackground(java.awt.Color.decode("#ffffff"));
        lbl_input_mhs.setForeground(java.awt.Color.decode("#000000"));
        lbl_buat_kelas.setForeground(java.awt.Color.decode("#000000"));
        pnl_input_asisten.setBackground(java.awt.Color.decode("#30AD5B"));
        lbl_input_asisten.setForeground(java.awt.Color.decode("#ffffff"));
        lbl_title.setText("Input Data Asisten Dosen");
        muncul_input_asdos();
    }//GEN-LAST:event_lbl_input_asistenMouseClicked

    private void lbl_buat_kelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buat_kelasMouseClicked
        pnl_input_mhs.setBackground(java.awt.Color.decode("#ffffff"));
        pnl_input_asisten.setBackground(java.awt.Color.decode("#ffffff"));
        lbl_input_mhs.setForeground(java.awt.Color.decode("#000000"));
        lbl_input_asisten.setForeground(java.awt.Color.decode("#000000"));
        pnl_buat_kelas.setBackground(java.awt.Color.decode("#30AD5B"));
        lbl_buat_kelas.setForeground(java.awt.Color.decode("#ffffff"));
        lbl_title.setText("Buat Kelas Praktikum");
        muncul_buat_kelas();
    }//GEN-LAST:event_lbl_buat_kelasMouseClicked

    private void muncul_input_mhs(){
        anu_input  = new input_data_mhs();
        
        //remove panel
        panel_alas1.removeAll();
        panel_alas1.repaint();
        panel_alas1.revalidate();
        
        //add panel
        panel_alas1.add(anu_input);
        panel_alas1.repaint();
        panel_alas1.revalidate();
    }
    
    private void muncul_buat_kelas(){
        anu_kelas  = new buat_kelas();
        
        //remove panel
        panel_alas1.removeAll();
        panel_alas1.repaint();
        panel_alas1.revalidate();
        
        //add panel
        panel_alas1.add(anu_kelas);
        panel_alas1.repaint();
        panel_alas1.revalidate();
    }
    
    private void muncul_input_asdos(){
        anu_asdos = new input_asdos();
        
        //remove panel
        panel_alas1.removeAll();
        panel_alas1.repaint();
        panel_alas1.revalidate();
        
        //add panel
        panel_alas1.add(anu_asdos);
        panel_alas1.repaint();
        panel_alas1.revalidate();
    }
    
    private void logout() {
        login = new login_operator();
        login.setVisible(true);
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_opt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_opt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_opt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_opt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_opt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_buat_kelas;
    private javax.swing.JLabel lbl_input_asisten;
    private javax.swing.JLabel lbl_input_mhs;
    private javax.swing.JLabel lbl_logout;
    public javax.swing.JLabel lbl_title;
    private javax.swing.JPanel panel_alas;
    private javax.swing.JPanel panel_alas1;
    public javax.swing.JPanel pnl_atas;
    private javax.swing.JPanel pnl_buat_kelas;
    private javax.swing.JPanel pnl_input_asisten;
    private javax.swing.JPanel pnl_input_mhs;
    private javax.swing.JPanel pnl_logout;
    // End of variables declaration//GEN-END:variables
}
