/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bagian_operator;

/**
 *
 * @author R
 */
public class input_asdos extends javax.swing.JPanel {

    /**
     * Creates new form input_asdos
     */
    public input_asdos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_alas = new javax.swing.JPanel();
        txt_matkul1 = new javax.swing.JLabel();
        txt_tahun = new javax.swing.JLabel();
        txt_hari = new javax.swing.JLabel();
        txt_kredit = new javax.swing.JLabel();
        txt_kelas = new javax.swing.JLabel();
        txt_id_matkul = new javax.swing.JLabel();
        txt_matkul = new javax.swing.JLabel();
        et_tahun = new javax.swing.JTextField();
        et_hari = new javax.swing.JTextField();
        et_kredit = new javax.swing.JTextField();
        et_kelas = new javax.swing.JTextField();
        btn_buat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jPanel1.setPreferredSize(new java.awt.Dimension(1093, 652));

        panel_alas.setBackground(new java.awt.Color(245, 245, 245));
        panel_alas.setLayout(null);

        txt_matkul1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_matkul1.setText("Asisten 2");
        panel_alas.add(txt_matkul1);
        txt_matkul1.setBounds(30, 330, 230, 40);

        txt_tahun.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_tahun.setText("NIM");
        panel_alas.add(txt_tahun);
        txt_tahun.setBounds(30, 450, 230, 40);

        txt_hari.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_hari.setText("Nama Asisten 2");
        panel_alas.add(txt_hari);
        txt_hari.setBounds(30, 380, 230, 40);

        txt_kredit.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_kredit.setText("NIM");
        panel_alas.add(txt_kredit);
        txt_kredit.setBounds(30, 240, 230, 40);

        txt_kelas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_kelas.setText("Nama Asisten 1");
        panel_alas.add(txt_kelas);
        txt_kelas.setBounds(30, 170, 230, 40);

        txt_id_matkul.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_id_matkul.setText("ID Mata Kuliah");
        panel_alas.add(txt_id_matkul);
        txt_id_matkul.setBounds(30, 50, 230, 40);

        txt_matkul.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txt_matkul.setText("Asisten 1");
        panel_alas.add(txt_matkul);
        txt_matkul.setBounds(30, 120, 230, 40);

        et_tahun.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        et_tahun.setToolTipText("Cari");
        panel_alas.add(et_tahun);
        et_tahun.setBounds(280, 450, 490, 40);

        et_hari.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        et_hari.setToolTipText("Cari");
        panel_alas.add(et_hari);
        et_hari.setBounds(280, 380, 490, 40);

        et_kredit.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        et_kredit.setToolTipText("Cari");
        panel_alas.add(et_kredit);
        et_kredit.setBounds(280, 240, 490, 40);

        et_kelas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        et_kelas.setToolTipText("Cari");
        panel_alas.add(et_kelas);
        et_kelas.setBounds(280, 170, 490, 40);

        btn_buat.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_buat.setForeground(new java.awt.Color(255, 255, 255));
        btn_buat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buat.setText("Simpan");
        btn_buat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buatMouseClicked(evt);
            }
        });
        panel_alas.add(btn_buat);
        btn_buat.setBounds(850, 210, 180, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bagian_operator/icon/Button_Connect.png"))); // NOI18N
        panel_alas.add(jLabel5);
        jLabel5.setBounds(850, 210, 180, 50);

        btn_clear.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_clear.setText("Clear");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });
        panel_alas.add(btn_clear);
        btn_clear.setBounds(850, 280, 180, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bagian_operator/icon/Button_Dis.png"))); // NOI18N
        panel_alas.add(jLabel6);
        jLabel6.setBounds(850, 280, 180, 50);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PBO", " " }));
        panel_alas.add(jComboBox1);
        jComboBox1.setBounds(280, 50, 490, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buatMouseClicked

    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_buat;
    private javax.swing.JLabel btn_clear;
    private javax.swing.JTextField et_hari;
    private javax.swing.JTextField et_kelas;
    private javax.swing.JTextField et_kredit;
    private javax.swing.JTextField et_tahun;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_alas;
    public javax.swing.JLabel txt_hari;
    public javax.swing.JLabel txt_id_matkul;
    public javax.swing.JLabel txt_kelas;
    private javax.swing.JLabel txt_kredit;
    public javax.swing.JLabel txt_matkul;
    public javax.swing.JLabel txt_matkul1;
    public javax.swing.JLabel txt_tahun;
    // End of variables declaration//GEN-END:variables
}
