/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.echo.clientserver.sayhello.client_mahasiswa;

import com.echo.clientserver.sayhello.client_asdos.asdos_absen;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi_client.ip_form;

/**
 *
 * @author R
 */
public class home_mahasiswa extends javax.swing.JPanel {
    String waktu;
    /**
     * Creates new form home_mahasiswa
     */
    public home_mahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_alas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_View = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_konek = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1090, 650));

        panel_alas.setBackground(new java.awt.Color(255, 255, 255));
        panel_alas.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tugas-1.png"))); // NOI18N
        panel_alas.add(jLabel12);
        jLabel12.setBounds(610, 180, 110, 120);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("HISTORY");
        panel_alas.add(jLabel13);
        jLabel13.setBounds(530, 310, 270, 29);

        btn_View.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_View.setForeground(new java.awt.Color(255, 255, 255));
        btn_View.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_View.setText("View");
        btn_View.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ViewMouseClicked(evt);
            }
        });
        panel_alas.add(btn_View);
        btn_View.setBounds(585, 365, 170, 35);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button_Dis.png"))); // NOI18N
        panel_alas.add(jLabel14);
        jLabel14.setBounds(580, 360, 176, 50);

        btn_konek.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btn_konek.setForeground(new java.awt.Color(255, 255, 255));
        btn_konek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_konek.setText("Upload");
        btn_konek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_konek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_konekMouseClicked(evt);
            }
        });
        panel_alas.add(btn_konek);
        btn_konek.setBounds(185, 375, 160, 35);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button_Connect.png"))); // NOI18N
        panel_alas.add(jLabel8);
        jLabel8.setBounds(180, 370, 176, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tugas.png"))); // NOI18N
        panel_alas.add(jLabel9);
        jLabel9.setBounds(210, 190, 110, 120);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("WORK");
        panel_alas.add(jLabel11);
        jLabel11.setBounds(230, 320, 80, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dasar_Connect.png"))); // NOI18N
        panel_alas.add(jLabel6);
        jLabel6.setBounds(130, 170, 273, 278);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dasar_Dis.png"))); // NOI18N
        panel_alas.add(jLabel7);
        jLabel7.setBounds(530, 170, 280, 280);

        jTextField1.setText("jTextField1");
        panel_alas.add(jTextField1);
        jTextField1.setBounds(170, 60, 180, 40);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_alas.add(jButton1);
        jButton1.setBounds(380, 60, 72, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_alas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_alas, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ViewMouseClicked
        // TODO add your handling code here:
        //        try {
            //            // TODO add your handling code here:
            //            //gak_bisa();
            //        } catch (RemoteException ex) {
            //            Logger.getLogger(login_form.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        muncul_history();
    }//GEN-LAST:event_btn_ViewMouseClicked

    private void btn_konekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_konekMouseClicked
        // TODO add your handling code here:
        //        try {
            //            // TODO add your handling code here:
            //            //bisa();
            //            //ubah_status_online();
            //        } catch (RemoteException ex) {
            //            Logger.getLogger(login_form.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_btn_konekMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void muncul_history(){
        history_mahasiswa mahasiswa_history  = new history_mahasiswa();
        mahasiswa_history.setVisible(true);
        this.setEnabled(false);   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_View;
    private javax.swing.JLabel btn_konek;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panel_alas;
    // End of variables declaration//GEN-END:variables
}
